### PR TITLE
Allow svirt_sandbox_file_t as an entrypoint for spc_t

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by lsm5** [comment]
@rhatdan shouldn't this be going to @projectatomic/docker-selinux instead?

**Comment by rhatdan** [comment]
@lsm5 Where are you pulling from?  Did we make projectatomic/docker-selinux the upstream?

**Comment by lsm5** [comment]
hmm, so what went into rhel dev freeze was from fedora-cloud, but what's going into fedora is from projectatomic, I guess let's finalize on one and shut the other down. Just that everything in the docker spec file is pulled from @projectatomic, so I'm hoping we could use that for docker-selinux as well.

**Comment by rhatdan** [comment]
Yes lets move everything to projectatomic.  Is there some way to eliminate the upstream from this?

**Comment by lsm5** [comment]
who's upstream exactly in this case?

**Comment by rhatdan** [comment]
Lets

**Comment by rhatdan** [comment]
lets say projectatomic is the upstream. Latest code is checked into the fedora and rhel-1.10 branches.

For some reason when I checked in my changes they were going directly here.  I just forked this build so that in the future, I will check into rhatdan/docker-selinux and push patches here.

**Pull request closed without merging**
