### PR TITLE
Rhel 1.10

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by wrabcak** [comment]
Same opinion like in Fedora pull request.

**Comment by rhatdan** [comment]
I believe master or fedora should be pure and should not have the hacks that we have had to add for rhel.  docker-selinux that I install on Rawhide should be clean.  Hopefully similarly for fedora 23,  Then we can maintain patches for the rhel release until we can get the fixes into selinux-policy say around rhel7.3 time frame.

**Comment by rhatdan** [comment]
Lukas can we get these merged?

**Comment by rhatdan** [comment]
Looks like this is merged.

**Pull request closed without merging**
