### PR TITLE
Make docker_t unconfined for now, need to fix transitions from docker_t ...

### PR DESCRIPTION
**Pull request by rhatdan**
...to spc_t when executing containers

### CODE REVIEW

**Comment by rhatdan** [comment]
Can I get this merged?

**Comment by lsm5** [comment]
ping @wrabcak

**Comment by lsm5** [comment]
@rhatdan you should now have owner rights on this repo

**Comment by wrabcak** [comment]
Hi, 
Dan your invitation to this organisation and also this repo is in pending state, so please check "somewhere" your invitations and accept it. 

Next thing, 
Last night I made rawhide build, so all interfaces are in selinux policy package right now. Could you remove gen_require blocks? Then I merge this pull request

**Comment by rhatdan** [comment]
Except we are stuck on RHEL then?  We need to get this updated policy into the docker-1.6 release, which is frozen on Friday.

**Comment by rhatdan** [comment]
@wrabcak I joined the Fedora-cloud this morning.

**Pull request merged**
